# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1892eccf637b752d4aa5f4adfc59044c2b29b53edf02ef90f420de0ca496e3072ccaedd838e1e69ac47abb06e4b69dbe83f0b2b71df16bc236744e2b87ce74a

test:
  secret_key_base: 0ca94c6613043e1dc499bf5b42866a8dd18f685d1ea19df6f2fdce4334d4058a70ed42db228a554abe2bb0a3e9461f5d95211285fcbcc38f06f6657ae0c5f201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
